/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import '@ionic/core';


import {
  St3DCardCarousel as St3dCardCarousel
} from './components/st-3D-card-carousel/st-3D-card-carousel';

interface HTMLSt3dCardCarouselElement extends St3dCardCarousel, HTMLElement {
}
declare var HTMLSt3dCardCarouselElement: {
  prototype: HTMLSt3dCardCarouselElement;
  new (): HTMLSt3dCardCarouselElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "st-3d-card-carousel": HTMLSt3dCardCarouselElement;
  }
  interface ElementTagNameMap {
      "st-3d-card-carousel": HTMLSt3dCardCarouselElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "st-3d-card-carousel": JSXElements.St3dCardCarouselAttributes;
      }
  }
  namespace JSXElements {
      export interface St3dCardCarouselAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          slides?: any
      }
  }
}


import {
  TestCarousel as TestCarousel
} from './components/test-carousel/test-carousel';

interface HTMLTestCarouselElement extends TestCarousel, HTMLElement {
}
declare var HTMLTestCarouselElement: {
  prototype: HTMLTestCarouselElement;
  new (): HTMLTestCarouselElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "test-carousel": HTMLTestCarouselElement;
  }
  interface ElementTagNameMap {
      "test-carousel": HTMLTestCarouselElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "test-carousel": JSXElements.TestCarouselAttributes;
      }
  }
  namespace JSXElements {
      export interface TestCarouselAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
      }
  }
}

