/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  St3DCardCarousel as St3dCardCarousel
} from './components/st-3D-card-carousel/st-3D-card-carousel';

declare global {
  interface HTMLSt3dCardCarouselElement extends St3dCardCarousel, HTMLElement {
  }
  var HTMLSt3dCardCarouselElement: {
    prototype: HTMLSt3dCardCarouselElement;
    new (): HTMLSt3dCardCarouselElement;
  };
  interface HTMLElementTagNameMap {
    "st-3d-card-carousel": HTMLSt3dCardCarouselElement;
  }
  interface ElementTagNameMap {
    "st-3d-card-carousel": HTMLSt3dCardCarouselElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "st-3d-card-carousel": JSXElements.St3dCardCarouselAttributes;
    }
  }
  namespace JSXElements {
    export interface St3dCardCarouselAttributes extends HTMLAttributes {
      
        slides?: any
    }
  }
}


import {
  TestCarousel as TestCarousel
} from './components/test-carousel/test-carousel';

declare global {
  interface HTMLTestCarouselElement extends TestCarousel, HTMLElement {
  }
  var HTMLTestCarouselElement: {
    prototype: HTMLTestCarouselElement;
    new (): HTMLTestCarouselElement;
  };
  interface HTMLElementTagNameMap {
    "test-carousel": HTMLTestCarouselElement;
  }
  interface ElementTagNameMap {
    "test-carousel": HTMLTestCarouselElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "test-carousel": JSXElements.TestCarouselAttributes;
    }
  }
  namespace JSXElements {
    export interface TestCarouselAttributes extends HTMLAttributes {
      
    }
  }
}

